{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-cardx
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/cardx_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/cardx/cardx_{{ version }}.tar.gz
  sha256: 78c0d8896b05170020bcd3b808dd1631fe4f56a5cc22c7f37800af4dfa7987da

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cards >=0.7.0
    - r-cli >=3.6.1
    - r-dplyr >=1.1.2
    - r-glue >=1.6.2
    - r-lifecycle >=1.0.3
    - r-rlang >=1.1.1
    - r-tidyr >=1.3.0
  run:
    - r-base
    - r-cards >=0.7.0
    - r-cli >=3.6.1
    - r-dplyr >=1.1.2
    - r-glue >=1.6.2
    - r-lifecycle >=1.0.3
    - r-rlang >=1.1.1
    - r-tidyr >=1.3.0

test:
  commands:
    - $R -e "library('cardx')"           # [not win]
    - "\"%R%\" -e \"library('cardx')\""  # [win]

about:
  home: https://github.com/insightsengineering/cardx
  license: Apache-2.0
  summary: Create extra Analysis Results Data (ARD) summary objects. The package supplements the simple ARD functions from the 'cards' package, exporting functions to put statistical results in the ARD format. These objects are used and re-used to construct summary tables, visualizations, and written reports.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
